### PR TITLE
@expede signs the CLA

### PR DESCRIPTION
**Pull request by expede**
If required, I'm happy to release what little IP I've contributed to the idea :P

### CODE REVIEW

**Comment by expede** [comment]
> First-time contributors need a maintainer to approve running workflows

Hmmm

@oed can you enable this? Or if you have the ability to merge it in: go ahead!

**Comment by oed** [comment]
Uh, the spellchecker failed on MultiDID. Any idea how to add an exception?

**Comment by expede** [comment]
haha I guess that's not in a typical dictionary (yet!) Add it to this file: https://github.com/ChainAgnostic/multidid/blob/main/.github/workflows/words-to-ignore.txt

**Comment by expede** [comment]
I guess needs approval to run again

**Comment by oed** [comment]
Still failing.
If you want to wait, I fixed the spelling errors in #2

**Pull request merged**
